apiVersion: apps/v1
kind: Deployment
metadata:
  name: botson
  labels:
    app: botson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: botson
  template:
    metadata:
      labels:
        app: botson
    spec:
      containers:
        - name: botson
          image: ssouthcity/botson:3c5ad3f5872f2083a5e289d6b2f7f3c08252b742
